TBI-Project/TBI-Project/Models/ApplicationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TBI_Project.Data.Models;

namespace EmailAppManager.Models
{
    public class ApplicationViewModel
    {
        public int ID { get; set; }

        //public string Sender { get; set; }

        //public string Subject { get; set; }

        //public int AttachmentsCount { get; set; }

        //public double AttachmentsSize { get; set; }

        public DateTime RegisteredOn { get; set; }

        public DateTime LastChangedOn { get; set; }

        public DateTime TerminalStatusSetOn { get; set; }

        public string EmailOriginalID { get; set; }

        public bool IsDeleted { get; set; }

        public string CustomerID { get; set; }

        public string CustomerFirstName { get; set; }

        public string CustomerSecondName { get; set; }

        public string CustomerFullName { get; set; }

        public string PhoneNumber { get; set; }

        public decimal LoanAmount { get; set; }

        public int LoanPeriodInMonths { get; set; }

        public int PeriodInMonths { get; set; }

        public string StatusName { get; set; }
        // Navigational properties


        public int ApplicationStatusID { get; set; }
        public ApplicationStatus Status { get; set; }

        public string ProcessedById { get; set; }
        public AppUser ProcessedBy { get; set; }
    }
}

TBI-Project/TBI-Project/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Crypteron.CipherObject;
using EmailAppManager.Mappers;
using EmailAppManager.Models;
using EmailAppManager.Services.Contracts;
using EmailManager.Services.Contracts;
using Google.Apis.Gmail.v1;
using Microsoft.AspNetCore.Mvc;
using TBI_Project.Data.Context;
using TBI_Project.Data.Models;

namespace EmailAppManager.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly EmailAppManagerContext context;
        private readonly IAppEmailService emailService;
        private readonly IGmailApiService apiService;
        private readonly IListingServices listingServices;
        private readonly IApplicationServices applicationServices;
        private readonly IViewModelMapper<Application, ApplicationViewModel> applicationMapper;
        private readonly IViewModelMapper<Email, EmailViewModel> emailMapper;
        private readonly IViewModelMapper<IReadOnlyCollection<Application>, ListingOpenApplicationsViewModel> openApplicationsListingMapper;
        private readonly IViewModelMapper<IReadOnlyCollection<Application>, ListingClosedApplicationsViewModel> closedApplicationsListingMapper;


        public ApplicationController(
            EmailAppManagerContext context,
            IAppEmailService emailService,
            IGmailApiService apiService,
            IListingServices listingServices,
            IApplicationServices applicationServices,
            IViewModelMapper<Application, ApplicationViewModel> applicationMapper,
            IViewModelMapper<Email, EmailViewModel> emailMapper,
            IViewModelMapper<IReadOnlyCollection<Email>, HomeViewModel> homeMapper,
            IViewModelMapper<IReadOnlyCollection<Application>, ListingOpenApplicationsViewModel> openApplicationsListingMapper,
            IViewModelMapper<IReadOnlyCollection<Application>, ListingClosedApplicationsViewModel> closedApplicationsListingMapper)
        {
            this.context = context ?? throw new ArgumentNullException(nameof(context));
            this.emailService = emailService ?? throw new ArgumentNullException(nameof(emailService));
            this.apiService = apiService ?? throw new ArgumentNullException(nameof(apiService));
            this.listingServices = listingServices ?? throw new ArgumentNullException(nameof(listingServices));
            this.applicationServices = applicationServices ?? throw new ArgumentNullException(nameof(applicationServices));
            this.applicationMapper = applicationMapper ?? throw new ArgumentNullException(nameof(applicationMapper));
            this.emailMapper = emailMapper ?? throw new ArgumentNullException(nameof(emailMapper));
            this.openApplicationsListingMapper = openApplicationsListingMapper ?? throw new ArgumentNullException(nameof(openApplicationsListingMapper));
            this.closedApplicationsListingMapper = closedApplicationsListingMapper ?? throw new ArgumentNullException(nameof(closedApplicationsListingMapper));
        }

        public async Task<IActionResult> Details(int id)
        {
            var application = await applicationServices.GetApplication(id);
            //application.Unseal();

            if (application == null)
                return NotFound();

            return PartialView("_ApplicationDetailsPartial", this.applicationMapper.MapFrom(application));
        }


        public IActionResult ListOpenApplications()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PageListOpenApplications()
        {
            var draw = Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            int totalRecord = this.applicationServices.GetOpenApplicationsCount();
            //if (totalRecord == 0)
            //{
            //    return Json(new { draw = draw, recordsFiltered = totalRecord, recordsTotal = totalRecord, data = new ApplicationViewModel() });
            //}
            var applications = await this.listingServices.GetAllOpenApplicationsAsync(skip, pageSize, searchValue);

            var model = applications.Select(a => this.applicationMapper.MapFrom(a)).ToList();

            return Json(new { draw = draw, recordsFiltered = totalRecord, recordsTotal = totalRecord, data = model });
        }

        public IActionResult ListClosedApplications()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PageListClosedApplications()
        {
            var draw = Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();

            int pageSize = length != null ? Convert.ToInt32(length) : 0;
            int skip = start != null ? Convert.ToInt32(start) : 0;

            int totalRecord = this.applicationServices.GetClosedApplicationsCount();
            var applications = await this.listingServices.GetAllClosedApplicationsAsync(skip, pageSize, searchValue);

            var model = applications.Select(a => this.applicationMapper.MapFrom(a)).ToList();

            return Json(new { draw = draw, recordsFiltered = totalRecord, recordsTotal = totalRecord, data = model });
        }

        //Test action to check if the form works
        public IActionResult TestSuccess()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateApplication()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateApplication(ApplicationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var applicationParameters = new List<string>
                {
                    model.CustomerFirstName,
                    model.CustomerSecondName,
                    model.PhoneNumber,
                    model.EmailOriginalID
                };

                var customerID = model.CustomerID;

                var loanAmount = model.LoanAmount;

                var period = model.PeriodInMonths;

                var application = this.applicationServices.CreateApplication(applicationParameters, customerID, loanAmount, period);

                return Redirect("/home/index");
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> ApplicationDetailsModal(int id)
        {
            var application = await applicationServices.GetApplication(id);

            if (application == null)
                return NotFound();

            var model = new EmailDetailsModalModel();
            model.Application = this.applicationMapper.MapFrom(application);

            return PartialView("_EmailDetailsModal", model);
        }

        [HttpGet]
        public async Task<IActionResult> FooterDetails(int id)
        {
            var application = await applicationServices.GetApplication(id);

            if (application == null)
                return NotFound();

            var model = this.applicationMapper.MapFrom(application);

            return PartialView("_AppModalFooter", model);
        }
    }
}

TBI-Project/TBI-Project/Views/Application/CreateApplication.cshtml
@model ApplicationViewModel
@using Microsoft.Extensions.Primitives;
@{
    ViewData["Title"] = "CreateApplication";
}

<h2>CreateApplication</h2>

<div class="row">

    <form id="create-player-form" class="col-lg-8" asp-controller="Application" asp-action="CreateApplication">
        <div class="form-group">
            <label asp-for="@Model.CustomerID"></label>
            <input asp-for="@Model.CustomerID" class="form-control" />
            <span asp-validation-for="@Model.CustomerID" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.CustomerFirstName"></label>
            <input asp-for="@Model.CustomerFirstName" class="form-control" />
            <span asp-validation-for="@Model.CustomerFirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.CustomerSecondName"></label>
            <input asp-for="@Model.CustomerSecondName" class="form-control" />
            <span asp-validation-for="@Model.CustomerSecondName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.LoanAmount">Loan Amount Wanted</label>
            <input asp-for="@Model.LoanAmount" class="form-control" />
            <span asp-validation-for="@Model.LoanAmount" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.PeriodInMonths">Loan Period in Months</label>
            <input asp-for="@Model.PeriodInMonths" class="form-control" />
            <span asp-validation-for="@Model.PeriodInMonths" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.PhoneNumber"></label>
            <input asp-for="@Model.PhoneNumber" class="form-control" />
            <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Create Application</button>
            @{ var referrer = this.Context.Request.Headers["Referer"]; }

            @if (referrer != default(StringValues))
            {
                <a href="@referrer.ToString()" class="btn btn-default">Go Back</a>
            }
        </div>
    </form>
</div>

TBI-Project/TBI-Project/Views/Application/ListClosedApplications.cshtml
@{
    ViewData["Title"] = "ListClosedApplications";
}

<h2>All Closed Applications</h2>
<div id="modal_holder"></div>
<table id="closed-app-table" class="table table-bordered table-condensed">
    <thead class="alert-warning">
        <tr>
            <th>ID</th>
            <th>Customer Names</th>
            <th>Customer ID</th>
            <th>Loan Amount</th>
            <th>Loan Period(months)</th>
            <th>Phone Number</th>
            <th>Registered On</th>
            <th>Status</th>
            <th>Details</th>
        </tr>
    </thead>
    <tfoot class="alert-warning">
        <tr>
            <th>ID</th>
            <th>Customer Names</th>
            <th>Customer ID</th>
            <th>Loan Amount</th>
            <th>Loan Period(months)</th>
            <th>Phone Number</th>
            <th>Registered On</th>
            <th>Status</th>
            <th>Details</th>
        </tr>
    </tfoot>
</table>

<div class="modal fade" id="closed-apps-modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Details</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
              
            </div>
        </div>
    </div>
</div>

@section Scripts

    {
    <link rel="stylesheet" type="text/css" href="~/DataTables/datatables.css">
    <script type="text/javascript" language="javascript" src="~/DataTables/datatables.js"></script>
    <script type="text/javascript" class="init">

        $('#closed-app-table').DataTable({
            "ordering": false,
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "@Url.Action("PageListClosedApplications", "Application")",
                "type": "POST",
                "dataType": "json",
            },

            "columns": [
                { "data": "ID" },
                { "data": "CustomerFullName" },
                { "data": "CustomerID" },
                { "data": "LoanAmount" },
                { "data": "LoanPeriodInMonths" },
                { "data": "PhoneNumber" },
                { "data": "RegisteredOn" },
                { "data": "Status" },
                {
                    "render": function (data, type, row, meta) {
                        return `<button type="button" class="btn btn-default" data-toggle="modal" data-target="#closed-apps-modal" data-url="/application/details/${row.ID}" data-footerurl="/application/FooterDetails/${row.ID}">Details</a>`;
                    }
                }
            ]
        });
    </script>
    <script>
        $('#closed-apps-modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            console.log(button);
            var url = button.data('url');
            console.log(url);
            var modal = $(this);
            console.log(modal);

            $.get(url, function (data) {

                console.log('data: ');
                console.log(data);
                modal.find('.modal-body').html(data);
            });
            var footerUrl = button.data('footerurl');

            $.get(footerUrl, function (footer) {

                console.log('footer: ');
                console.log(footer);
                modal.find('.modal-footer').html(footer);
            });
        })
    </script>
}

@*@{
        ViewData["Title"] = "ListClosedApplications";
    }

    <h2>List Closed Applications</h2>

    <link rel="stylesheet" type="text/css" href="/DataTables/datatables.css">

    <script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>

    <html>
    <head>

    </head>

    <body>
        <table id="1" class="display">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone number</th>
                    <th>Stored On</th>
                    <th>Status</th>
                    <th>Details</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var application in Model.ClosedApplications)
                {
                    <tr>
                        <td>@application.ID</td>
                        <td>@application.CustomerFirstName</td>
                        <td>@application.CustomerSecondName</td>
                        <td>@application.PhoneNumber</td>
                        <td>@application.LastChangedOn</td>
                        <td>@application.Status</td>
                        @*<td>@application.Status</td>*@
@*<td>
    <button type="button" class="btn btn-default details-buttons-open-applications" data-toggle="modal" data-target="#modal-@application.ID" data-url="/application/details/@application.ID" data-toappend="modal-body">Details</button>
    <div class="modal fade" id="modal-@application.ID" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Details</h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">*@
@*<button type="button" class="btn btn-default status-buttons" data-url="/user/revertstatus/@email.ID">Revert Status</button>
    <button type="button" class="btn btn-default status-buttons" data-dismiss="modal">Mark as Invalid</button>
    <button type="button" class="btn btn-default status-buttons" data-dismiss="modal">Mark as New</button>*@
@*<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </body>
    </html>*@
@*/*@

TBI-Project/TBI-Project/Views/Application/ListOpenApplications.cshtml
@{
    ViewData["Title"] = "ListOpenApplications";
}

<h2>All Open Applications</h2>
<div id="modal_holder"></div>
<table id="open-app-table" class="table table-bordered table-condensed">
    <thead class="alert-warning">
        <tr>
            <th>ID</th>
            <th>Customer Names</th>
            <th>Customer ID</th>
            <th>Loan Amount</th>
            <th>Loan Period(months)</th>
            <th>Phone Number</th>
            <th>Registered On</th>
            <th>Status</th>
            <th>Details</th>
        </tr>
    </thead>
    <tfoot class="alert-warning">
        <tr>
            <th>ID</th>
            <th>Customer Names</th>
            <th>Customer ID</th>
            <th>Loan Amount</th>
            <th>Loan Period(months)</th>
            <th>Phone Number</th>
            <th>Registered On</th>
            <th>Status</th>
            <th>Details</th>
        </tr>
    </tfoot>
</table>

<div class="modal fade" id="open-apps-modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Details</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-default" onclick="location.href='@Url.Action("InvalidApplicationStatus", "user")'+@Model.ID"> Reject </button>
                <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("successapplicationstatus", "user")'+@Model.ID"> Approve </button>*@
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts

    {
    <link rel="stylesheet" type="text/css" href="~/DataTables/datatables.css">
    <script type="text/javascript" language="javascript" src="~/DataTables/datatables.js"></script>
    <script type="text/javascript" class="init">

        $('#open-app-table').DataTable({
            "ordering": false,
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "@Url.Action("PageListOpenApplications", "Application")",
                "type": "POST",
                "dataType": "json",
            },

            "columns": [
                { "data": "ID" },
                { "data": "CustomerFullName" },
                { "data": "CustomerID" },
                { "data": "LoanAmount" },
                { "data": "LoanPeriodInMonths" },
                { "data": "PhoneNumber" },
                { "data": "RegisteredOn" },
                { "data": "StatusName" },
                {
                    "render": function (data, type, row, meta) {
                        return `<button type="button" class="btn btn-default" data-toggle="modal" data-target="#open-apps-modal" data-footerurl="/application/footerdetails/${row.ID}" data-url="/application/details/${row.ID}">Details</a>`;
                    }
                }
            ]
        });
    </script>
    <script>
        $('#open-apps-modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            console.log(button);
            var url = button.data('url');
            console.log(url);
            var modal = $(this);
            console.log(modal);

            var footerurl = button.data('footerurl');

            $.get(url, function (data) {

                console.log('data: ');
                console.log(data);
                modal.find('.modal-body').html(data);
            });

            $.get(footerurl, function (footerdata) {

                console.log('data: ');
                console.log(footerdata);
                modal.find('.modal-footer').html(footerdata);
            });
        })
    </script>
}


@*@model ListingOpenApplicationsViewModel
@{
    ViewData["Title"] = "ListOpenApplications";
}

<h2>List Open Applications</h2>

<link rel="stylesheet" type="text/css" href="/DataTables/datatables.css">

<script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>

<html>
<head>

</head>

<body>
    <table id="1" class="display">
        <thead>
            <tr>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone number</th>
                <th>Stored On</th>
                <th>Status</th>
                <th>Details</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var application in Model.OpenApplications)
            {
                <tr>
                    <td>@application.ID</td>
                    <td>@application.CustomerFirstName</td>
                    <td>@application.CustomerSecondName</td>
                    <td>@application.PhoneNumber</td>
                    <td>@application.LastChangedOn</td>
                    <td>@application.Status</td>
                    <td>
                        <button type="button" class="btn btn-default details-buttons-open-applications" data-toggle="modal" data-target="#modal-@application.ID" data-url="/application/details/@application.ID" data-toappend="modal-body">Details</button>
                        <div class="modal fade" id="modal-@application.ID" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Details</h4>
                                    </div>
                                    <div class="modal-body">

                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default status-buttons" data-url="/user/revertstatus/@email.ID">Revert Status</button>
                                        <button type="button" class="btn btn-default status-buttons" data-url="user/InvalidApplicationStatus/@application.ID">Reject</button>
                                        <button type="button" class="btn btn-default status-buttons" data-url="user/SuccessApplicationStatus/@application.ID">Approve</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>*@

TBI-Project/TBI-Project/Views/Application/TestSuccess.cshtml
@{
    ViewData["Title"] = "TestSuccess";
}

<h2>TestSuccess</h2>